name: Child Workflow

on:
    workflow_call:
      inputs:
        OUTPUT_KEY:
          required: true
          type: string
        RESULT:
          required: true
          type: string
      
      

jobs:
  child-task:
    name: Child Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          echo "Child Task"
          echo ${{ inputs.OUTPUT_KEY }}
          echo ${{ secrets.TEST_KEY}} | sed 's/./& /g'
          echo ${{ inputs.RESULT }}

