name: Notify Slack on New Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Tag and Commit Info
        id: tag_info
        run: |
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          commit_hash=$(git rev-list -n 1 $tag)
          commit_message=$(git log -1 --pretty=%B $commit_hash)

          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "commit_hash=$commit_hash" >> $GITHUB_OUTPUT
          echo "commit_message=$commit_message" >> $GITHUB_OUTPUT

      - name: Send Slack Notification
        run: |
          payload=$(jq -n --arg tag "${{ steps.tag_info.outputs.tag }}" \
                         --arg commit_hash "${{ steps.tag_info.outputs.commit_hash }}" \
                         --arg commit_message "${{ steps.tag_info.outputs.commit_message }}" \
                         --arg repo "${{ github.repository }}" \
                         '{
                           "text": "🎉 A new tag has been created in *\($repo)*:\n*Tag:* `\($tag)`\n*Commit Hash:* `\($commit_hash)`\n*Commit Message:* \($commit_message)"
                         }')

          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
