name: Parent

on:
  push:
    branches:
      - main

jobs:
  parent-task:
    name: Parent Task
    runs-on: ubuntu-latest
    outputs:
      output_key: ${{ steps.parent-task.outputs.output_key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        env:
          TEST_KEY: ${{secrets.TEST_KEY}}
        id: parent-task
        run: |
          echo "Parent Task"
          echo ${{secrets.TEST_KEY}} | sed 's/./& /g'
          echo "output_key=thisisoutputkey" >> "$GITHUB_OUTPUT"
      - name: Use GitHub Script
        id: script-step
        uses: actions/github-script@v6
        with:
          script: |
            return { status: "success", timestamp: new Date().toISOString() };
        
      - name: Display Script Outputs
        run: |
          echo "Result: ${{ steps.script-step.outputs.result }}"
  
  another-task:
    name: Another Task 1
    runs-on: ubuntu-latest
    needs: [parent-task]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Another Test
        run: |
          echo "Another Task 1"
          echo ${{secrets.TEST_KEY}} | sed 's/./& /g'
          echo ${{ needs.parent-task.outputs.output_key }}
          echo ${{ needs.parent-task.outputs.output_key }} | sed 's/./& /g'

  child-task:
    name: Child Workflow
    needs: [parent-task]
    uses: ./.github/workflows/child-workflow.yml
    with:
      OUTPUT_KEY: ${{ needs.parent-task.outputs.output_key }}
      RESULT: ${{ steps.script-step.outputs.result }}
    secrets: inherit
