name: Parent

on:
  push:
    branches:
      - main

jobs:
  parent-task:
    name: Parent Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Child Workflow
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const childWorkflow = workflows.find(workflow => workflow.name === 'Child');
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: childWorkflow.id
            });
      - name: Test
        run: |
          echo "Parent Task"
          echo $TEST_KEY
      - name: Child Workflow
        uses: ./.github/workflows/child-workflow.yml
      