name: Parent

on:
  push:
    branches:
      - main

jobs:
  parent-task:
    name: Parent Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "Parent Task"
          echo $TEST_KEY
      - name: Child Workflow
        uses: ./.github/workflows/child-workflow.yml
      